name: "Build Docker Image"

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v1"
    - name: "Build Docker Image"
      "run": |
        docker login -u {{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
        docker build -t quay.io/johannweging/yavu:latest .
        docker push quay.io/johannweging/yavu:latest

on:
  push:
    branches:
      - master
  schedule:
  - "cron": "0 12 * * SAT"
